name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  merge_group:
    branches:
      - main
  workflow_dispatch:

env:
  CARGO_INCREMENTAL: "0"

jobs:
  fmt:
    name: Check Rust Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0  # v7.0.0
      - uses: actions-rust-lang/setup-rust-toolchain@166cdcfd11aee3cb47222f9ddb555ce30ddb9659 # v1.17.0
      - name: cargo fmt
        run: cargo fmt --check

  clippy:
    name: Lint Rust Code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0  # v7.0.0
      - uses: actions-rust-lang/setup-rust-toolchain@166cdcfd11aee3cb47222f9ddb555ce30ddb9659 # v1.17.0
      - name: Install Dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y libdbus-1-dev libxcb1-dev
      - uses: Swatinem/rust-cache@c19371144df3bb44fab255c43d04cbc2ab54d1c4  # v2.9.1
      - name: Clippy
        run: cargo clippy --workspace --all-targets -- -D warnings

  test:
    name: Build and Test (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0  # v7.0.0
      - uses: actions-rust-lang/setup-rust-toolchain@166cdcfd11aee3cb47222f9ddb555ce30ddb9659 # v1.17.0
      - name: Install Linux dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update -y
          sudo apt-get install -y libdbus-1-dev gnome-keyring libxcb1-dev
      - uses: Swatinem/rust-cache@c19371144df3bb44fab255c43d04cbc2ab54d1c4  # v2.9.1
      - name: Build and Test
        working-directory: crates
        env:
          RUST_MIN_STACK: 8388608
        run: |
          if [ "$RUNNER_OS" = "Linux" ]; then
            gnome-keyring-daemon --components=secrets --daemonize --unlock <<< 'foobar'
          fi
          cargo test --workspace -- --skip scenario_tests::scenarios::tests
          cargo test --workspace --jobs 1 scenario_tests::scenarios::tests
